static inline NSDictionary *GetAllTranslations(NSString *code) {
    if ([code isEqualToString:@"ar"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"وضع الشبح",
            @"READ_RECEIPT_SECTION_HEADER": @"إيصالات القراءة",
            @"MISC_SECTION_HEADER": @"متنوع",
            @"FILE_FIXER_SECTION_HEADER": @"إصلاح منتقي الملفات",
            @"FAKE_LOCATION_SECTION_HEADER": @"موقع وهمي",
            @"LANGUAGE_SECTION_HEADER": @"اللغة",
            @"CREDITS_SECTION_HEADER": @"الاعتمادات",
            @"DISABLE_ONLINE_STATUS_TITLE": @"تعطيل حالة الإنترنت",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"عدم عرض حالتك كأونلاين.",
            @"DISABLE_TYPING_STATUS_TITLE": @"تعطيل حالة الكتابة",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"عدم عرض أنك تقوم بكتابة رسالة.",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"تعطيل حالة تسجيل الفيديو",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"عدم عرض أنك تقوم بتسجيل فيديو.",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"تعطيل حالة تحميل الفيديو",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"إخفاء عند تحميل فيديو",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"تعطيل تسجيل الرسائل الصوتية",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"عدم عرض أنك تقوم بتسجيل رسالة صوتية.",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"تعطيل حالة تحميل الرسائل الصوتية",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"عدم عرض أنك تقوم بتحميل رسالة صوتية.",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"تعطيل حالة تحميل الصور",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"إخفاء عند تحميل صورة",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"تعطيل حالة تحميل الملفات",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"عدم عرض أنك تقوم بتحميل ملف.",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"تعطيل اختيار الموقع",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"عدم عرض أنك تقوم باختيار موقع.",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"تعطيل اختيار جهة الاتصال",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"عدم عرض أنك تقوم باختيار جهة اتصال.",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"تعطيل حالة اللعب",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"عدم عرض أنك تلعب لعبة.",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"تعطيل تسجيل الفيديو الدائري",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"عدم عرض أنك تقوم بتسجيل فيديو دائري.",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"تعطيل حالة تحميل الفيديو الدائري",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"تعطيل التحدث في المكالمات الجماعية",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"عدم عرض أنك تتحدث في مكالمة جماعية.",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"تعطيل اختيار الملصق",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"عدم عرض أنك تقوم باختيار ملصق.",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"تعطيل التفاعل مع الإيموجي",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"عدم عرض أنك تتفاعل مع إيموجي.",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"تعطيل إقرار الإيموجي",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"عدم عرض أنك قمت بإقرار الإيموجي.",
            @"READ_RECEIPTS": @"إيصالات القراءة",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"تعطيل إيصالات قراءة الرسائل",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"عدم إظهار أنك قرأت الرسالة.",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"تعطيل إيصالات قراءة القصص",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"عدم إظهار أنك شاهدت القصة.",
            @"MISC": @"متفرقات",
            @"DISABLE_ALL_ADS_TITLE": @"تعطيل جميع الإعلانات",
            @"DISABLE_ALL_ADS_SUBTITLE": @"إزالة الإعلانات والمحتوى الترويجي من التطبيق.",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"تمكين حفظ المحتوى المحمي",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"تجاوز القيود وحفظ المحتوى المحمي.",
            @"ANTI_REVOKE_TITLE": @"مانع حذف الرسائل",
            @"ANTI_REVOKE_SUBTITLE": @"إبقاء الرسائل في المحادثة حتى بعد حذفها من قِبَل المُرسِل.",
            @"ANTI_SCREENSHOT_TITLE": @"إخفاء إشعار لقطة الشاشة",
            @"ANTI_SCREENSHOT_SUBTITLE": @"منع إرسال إشعار التقاط لقطة الشاشة في المحادثات السرية والقنوات المحمية.",
            @"FIX_FILE_PICKER_TITLE": @"إصلاح منتقي الملفات",
            @"FIX_FILE_PICKER_SUBTITLE": @"يصلح المشكلة التي تمنع اختيار الملفات من تطبيق الملفات في النسخ الجانبية",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"مسح ذاكرة منتقي الملفات المؤقتة",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"لأن منتقي الملفات ينسخ الملفات إلى مجلد مؤقت، يجب مسحها يدوياً",
            @"CACHE_CLEAR_WARNING_TITLE": @"تأكيد",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"هل أنت متأكد؟",
            @"ENABLE_FAKE_LOCATION_TITLE": @"تمكين تزييف الموقع",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"يسمح لك بتزييف موقع GPS الخاص بجهازك",
            @"SELECT_FAKE_LOCATION_TITLE": @"اختر الموقع",
            @"APPLY": @"تطبيق",
            @"APPLY_CHANGES": @"هل أنت متأكد أنك تريد تطبيق هذه التغييرات؟",
            @"OK": @"موافق",
            @"CANCEL": @"إلغاء",
            @"AUTHOR_MESSAGE": @"هذا التعديل على تيليجرام مخصص للاستخدام الشخصي والتعليمي فقط. نحن لسنا تابعين لتيليجرام بأي شكل من الأشكال. جميع العلامات التجارية، بما في ذلك اسم تيليجرام وشعاره، تعود لأصحابها. لا تستخدم هذا التعديل لكسر القوانين أو القيام بأي شيء مريب أو مخالف لشروط استخدام تيليجرام — نحن غير مسؤولين إذا حدث أي شيء غير متوقع. استخدمه على مسؤوليتك الخاصة.\n\nأيضًا... إذا أعجبك، قل شيئًا. أنا حرفيًا أعيش على التقدير.\n\nوإذا كنت ترغب في دعمي بالتبرع بدولار أو اثنين، تواصل معي على تيليجرام.",
        };
    }
    if ([code isEqualToString:@"ja"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"ゴーストモード",
            @"READ_RECEIPT_SECTION_HEADER": @"既読通知",
            @"MISC_SECTION_HEADER": @"その他",
            @"FILE_FIXER_SECTION_HEADER": @"ファイル選択の修正",
            @"FAKE_LOCATION_SECTION_HEADER": @"位置情報の偽装",
            @"LANGUAGE_SECTION_HEADER": @"言語",
            @"CREDITS_SECTION_HEADER": @"クレジット",
            @"DISABLE_ONLINE_STATUS_TITLE": @"オンライン表示を無効化",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"他のユーザーにオンライン状態を表示しません。",
            @"DISABLE_TYPING_STATUS_TITLE": @"入力中表示を無効化",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"メッセージ入力中の表示を隠します。",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"動画録画中表示を無効化",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"動画を録画中であることを隠します。",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"動画アップロード中表示を無効化",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"動画をアップロード中であることを隠します",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"ボイスメッセージ録音中表示を無効化",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"ボイスメッセージを録音中であることを隠します。",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"ボイスメッセージアップロード中表示を無効化",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"ボイスメッセージをアップロード中であることを隠します。",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"写真アップロード中表示を無効化",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"写真をアップロード中であることを隠します",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"ファイルアップロード中表示を無効化",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"ファイルをアップロード中であることを隠します。",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"位置情報選択中表示を無効化",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"位置情報を選択中であることを隠します。",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"連絡先選択中表示を無効化",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"連絡先を選択中であることを隠します。",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"ゲームプレイ中表示を無効化",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"ゲームプレイ中であることを隠します。",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"ラウンド動画録画中表示を無効化",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"ラウンド動画を録画中であることを隠します。",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"ラウンド動画アップロード中表示を無効化",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"グループ通話発言中表示を無効化",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"グループ通話で発言中であることを隠します。",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"ステッカー選択中表示を無効化",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"ステッカーを選択中であることを隠します。",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"絵文字操作中表示を無効化",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"絵文字を操作中であることを隠します。",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"絵文字リアクション表示を無効化",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"メッセージに絵文字でリアクションしたことを隠します。",
            @"READ_RECEIPTS": @"既読通知",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"メッセージ既読通知を無効化",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"メッセージを読んだことを相手に通知しません。",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"ストーリー既読通知を無効化",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"ストーリーを見たことを相手に通知しません。",
            @"MISC": @"その他",
            @"DISABLE_ALL_ADS_TITLE": @"全ての広告を無効化",
            @"DISABLE_ALL_ADS_SUBTITLE": @"アプリからプロモーションコンテンツと広告を削除します。",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"保護されたコンテンツの保存を許可",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"保存が制限されているコンテンツも保存できるようにします。",
            @"ANTI_REVOKE_TITLE": @"メッセージ削除防止",
            @"ANTI_REVOKE_SUBTITLE": @"送信者がメッセージを削除してもチャットに残します。",
            @"ANTI_SCREENSHOT_TITLE": @"スクリーンショット通知を隠す",
            @"ANTI_SCREENSHOT_SUBTITLE": @"シークレットチャットや保護チャンネルでのスクリーンショット通知を送信しません。",
            @"FIX_FILE_PICKER_TITLE": @"ファイルピッカーを修正",
            @"FIX_FILE_PICKER_SUBTITLE": @"サイドロード版でファイルアプリからファイルを選択できない問題を修正します。",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"ファイルピッカーのキャッシュをクリア",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"ファイルピッカーはファイルを一時ディレクトリにコピーするため、手動でクリアする必要があります。",
            @"CACHE_CLEAR_WARNING_TITLE": @"確認",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"本当によろしいですか？",
            @"ENABLE_FAKE_LOCATION_TITLE": @"位置情報の偽装を有効化",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"デバイスのGPS位置情報を偽装することができます",
            @"SELECT_FAKE_LOCATION_TITLE": @"位置情報を選択",
            @"APPLY": @"適用",
            @"APPLY_CHANGES": @"これらの変更を適用してもよろしいですか",
            @"OK": @"OK",
            @"CANCEL": @"キャンセル",
            @"DISCLAIMER": @"免責事項",
            @"AUTHOR_MESSAGE": @"このTweakは個人的かつ教育目的のみで提供されており、Telegram とは一切関係がありません。Telegram の名称やロゴなどの商標はそれぞれの所有者に帰属します。違反行為や規約違反に使わないでください。何か問題が発生しても開発者は責任を負いません。すべて自己責任でご使用ください。\n \nそれと、もし気に入ったら何か感想をください。正直、評価が励みになります。\n \nまた、1～2ドル寄付してサポートしたい場合は、Telegramで連絡してください。",
        };
    }
    if ([code isEqualToString:@"en"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"Ghost Mode",
            @"READ_RECEIPT_SECTION_HEADER": @"Read Receipts",
            @"MISC_SECTION_HEADER": @"Privacy & Extras",
            @"FILE_FIXER_SECTION_HEADER": @"File Picker Fix",
            @"FAKE_LOCATION_SECTION_HEADER": @"Fake Location",
            @"LANGUAGE_SECTION_HEADER": @"Language",
            @"CREDITS_SECTION_HEADER": @"Credits",
            @"DISABLE_ONLINE_STATUS_TITLE": @"Hide Online Status",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"Prevent others from seeing when you are online.",
            @"DISABLE_TYPING_STATUS_TITLE": @"Hide Typing Status",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"Hide the 'typing…' indicator when composing a message.",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"Hide Recording Video Status",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"Hide the indicator when recording a video.",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"Hide Uploading Video Status",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"Hide the indicator when uploading a video.",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"Hide Voice Recording Status",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"Hide the indicator when recording a voice message.",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"Hide Voice Uploading Status",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"Hide the indicator when uploading a voice message.",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"Hide Uploading Photo Status",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"Hide the indicator when uploading a photo.",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"Hide Uploading File Status",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"Hide the indicator when uploading a file.",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"Hide Choosing Location Status",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"Hide the indicator when choosing a location to share.",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"Hide Choosing Contact Status",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"Hide the indicator when selecting a contact to share.",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"Hide Playing Game Status",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"Hide the indicator when playing an inline game.",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"Hide Recording Round Video Status",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"Hide the indicator when recording a round video message.",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"Hide Uploading Round Video Status",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_SUBTITLE": @"Hide the indicator when uploading a round video message.",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"Hide Speaking in Group Call Status",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"Hide the indicator when speaking in a group call.",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"Hide Choosing Sticker Status",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"Hide the indicator when picking a sticker.",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"Hide Emoji Interaction Status",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"Hide the indicator when interacting with emoji.",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"Hide Emoji Reaction Status",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"Hide the indicator when reacting with emoji to a message.",
            @"READ_RECEIPTS": @"Read Receipts",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"Disable Message Read Receipts",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"Others won't see that you've read their messages.",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"Disable Story View Receipts",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"Others won't see that you've viewed their stories.",
            @"MISC": @"Privacy & Extras",
            @"DISABLE_ALL_ADS_TITLE": @"Disable All Ads",
            @"DISABLE_ALL_ADS_SUBTITLE": @"Remove sponsored messages and promotional content from the app.",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"Save Restricted Media",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"Bypass forwarding restrictions — save and forward media from protected chats and channels.",
            @"ANTI_REVOKE_TITLE": @"Save Deleted Messages",
            @"ANTI_REVOKE_SUBTITLE": @"Keep messages in your chat even after the sender deletes them. Deleted messages stay visible to you.",
            @"ANTI_EDIT_TITLE": @"Save Original Edited Messages",
            @"ANTI_EDIT_SUBTITLE": @"When someone edits a message, the original text is preserved on your end. You'll always see what was first written.",
            @"ANTI_SCREENSHOT_TITLE": @"Disable Screenshot Notifications",
            @"ANTI_SCREENSHOT_SUBTITLE": @"Take screenshots in secret chats and protected channels without sending a notification to the other person.",
            @"ANTI_SELF_DESTRUCT_TITLE": @"View Disappearing Media Freely",
            @"ANTI_SELF_DESTRUCT_SUBTITLE": @"Open one-time and disappearing photos/videos without triggering the self-destruct timer. The media stays visible locally.",
            @"FIX_FILE_PICKER_TITLE": @"Fix File Picker",
            @"FIX_FILE_PICKER_SUBTITLE": @"Fixes the issue where you can't pick files from the Files app on sideloaded versions.",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"Clear File Picker Cache",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"File Picker copies files to a temp directory. Tap here to clear that cache and free up storage.",
            @"CACHE_CLEAR_WARNING_TITLE": @"Confirm",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"Are you sure you want to clear the file picker cache?",
            @"ENABLE_FAKE_LOCATION_TITLE": @"Enable Location Spoofing",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"Override your device's GPS and share a custom location instead.",
            @"SELECT_FAKE_LOCATION_TITLE": @"Select Fake Location",
            @"APPLY": @"Apply",
            @"APPLY_CHANGES": @"The app will close and restart to apply your changes. Continue?",
            @"OK": @"OK",
            @"CANCEL": @"Cancel",
            @"DISCLAIMER": @"Disclaimer",
            @"AUTHOR_MESSAGE": @"This Telegram tweak is for personal and educational use only. We are not affiliated with Telegram in any way. All trademarks, including the Telegram name and logo, belong to their respective owners. Don't use this to break rules or violate Telegram's terms — we're not responsible if things go sideways. Use at your own risk.\n\nMade by Lead Team",
        };
    }
    if ([code isEqualToString:@"es"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"Modo Fantasma",
            @"READ_RECEIPT_SECTION_HEADER": @"Confirmaciones de Lectura",
            @"MISC_SECTION_HEADER": @"Misceláneo",
            @"FILE_FIXER_SECTION_HEADER": @"Reparador de Selector de Archivos",
            @"FAKE_LOCATION_SECTION_HEADER": @"Ubicación Falsa",
            @"LANGUAGE_SECTION_HEADER": @"Idioma",
            @"CREDITS_SECTION_HEADER": @"Créditos",
            @"DISABLE_ONLINE_STATUS_TITLE": @"Desactivar estado en línea",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"No mostrar que estás en línea.",
            @"DISABLE_TYPING_STATUS_TITLE": @"Desactivar estado de escritura",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"No mostrar que estás escribiendo.",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"Desactivar estado de grabación de video",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"No mostrar que estás grabando un video.",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"Desactivar estado de carga de video",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"Ocultar al subir un video",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"Desactivar grabación de mensajes de voz",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"No mostrar que estás grabando un mensaje de voz.",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"Desactivar estado de carga de mensaje de voz",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"No mostrar que estás subiendo un mensaje de voz.",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"Desactivar estado de carga de foto",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"Ocultar al subir una foto",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"Desactivar estado de carga de archivo",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"No mostrar que estás subiendo un archivo.",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"Desactivar selección de ubicación",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"No mostrar que estás eligiendo una ubicación.",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"Desactivar selección de contacto",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"No mostrar que estás eligiendo un contacto.",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"Desactivar estado de juego",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"No mostrar que estás jugando.",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"Desactivar grabación de video redondo",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"No mostrar que estás grabando un video redondo.",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"Desactivar estado de carga de video redondo",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"Desactivar estado de habla en llamada grupal",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"No mostrar que estás hablando en una llamada grupal.",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"Desactivar selección de stickers",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"No mostrar que estás eligiendo un sticker.",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"Desactivar interacción con emojis",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"No mostrar que estás interactuando con un emoji.",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"Desactivar reconocimiento de emojis",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"No mostrar que has reconocido un emoji.",
            @"READ_RECEIPTS": @"Recibos de lectura",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"Desactivar recibos de lectura de mensajes",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"No mostrar que has leído el mensaje.",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"Desactivar recibos de lectura de historias",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"No mostrar que has visto la historia.",
            @"MISC": @"Varios",
            @"DISABLE_ALL_ADS_TITLE": @"Desactivar todos los anuncios",
            @"DISABLE_ALL_ADS_SUBTITLE": @"Eliminar los anuncios y el contenido patrocinado de la aplicación.",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"Activar guardado de contenido protegido",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"Eludir restricciones para guardar contenido protegido.",
            @"ANTI_REVOKE_TITLE": @"Anti-Revocación",
            @"ANTI_REVOKE_SUBTITLE": @"Mantén los mensajes en el chat aunque el remitente los elimine.",
            @"ANTI_SCREENSHOT_TITLE": @"Ocultar aviso de captura",
            @"ANTI_SCREENSHOT_SUBTITLE": @"Evita notificaciones de captura de pantalla en chats secretos y canales protegidos.",
            @"FIX_FILE_PICKER_TITLE": @"Reparar Selector de Archivos",
            @"FIX_FILE_PICKER_SUBTITLE": @"Soluciona el problema que impide seleccionar archivos desde la app Archivos en versiones instaladas manualmente",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"Borrar Caché del Selector de Archivos",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"Como el selector copia los archivos a un directorio temporal, debemos borrarlos manualmente",
            @"CACHE_CLEAR_WARNING_TITLE": @"Confirmar",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"¿Estás seguro?",
            @"ENABLE_FAKE_LOCATION_TITLE": @"Activar Ubicación Falsa",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"Permite falsificar la ubicación GPS del dispositivo",
            @"SELECT_FAKE_LOCATION_TITLE": @"Seleccionar Ubicación",
            @"APPLY": @"Aplicar",
            @"APPLY_CHANGES": @"¿Estás seguro de que quieres aplicar estos cambios?",
            @"OK": @"Aceptar",
            @"CANCEL": @"Cancelar",
            @"DISCLAIMER": @"Aviso legal",
            @"AUTHOR_MESSAGE": @"Este ajuste de Telegram es solo para uso personal y educativo. No estamos afiliados con Telegram de ninguna manera. Todas las marcas registradas, incluido el nombre y logo de Telegram, pertenecen a sus respectivos propietarios. No uses esto para romper reglas, hacer cosas sospechosas o violar los términos de Telegram — no nos hacemos responsables si algo sale mal. Úsalo bajo tu propio riesgo.\n\nAdemás... si te gusta, dilo. En serio, vivo del reconocimiento.\n\nY también... si quieres apoyarme donando uno o dos dólares, contáctame por Telegram.",
        };
    }
    if ([code isEqualToString:@"it"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"Modalità Fantasma",
            @"READ_RECEIPT_SECTION_HEADER": @"Conferme di lettura",
            @"MISC_SECTION_HEADER": @"Varie",
            @"FILE_FIXER_SECTION_HEADER": @"Correzione selezione file",
            @"FAKE_LOCATION_SECTION_HEADER": @"Posizione falsa",
            @"LANGUAGE_SECTION_HEADER": @"Lingua",
            @"CREDITS_SECTION_HEADER": @"Crediti",
            @"DISABLE_ONLINE_STATUS_TITLE": @"Disattiva stato online",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"Impedisci agli altri di vederti online.",
            @"DISABLE_TYPING_STATUS_TITLE": @"Disattiva stato di digitazione",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"Nascondi quando stai scrivendo messaggi.",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"Disattiva stato di registrazione video",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"Nascondi quando stai registrando un video.",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"Disattiva stato di caricamento video",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"Nascondi quando stai caricando un video",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"Disattiva stato di registrazione messaggio vocale",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"Nascondi quando stai registrando un messaggio vocale.",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"Disattiva stato di caricamento messaggio vocale",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"Nascondi quando stai caricando un messaggio vocale.",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"Disattiva stato di caricamento foto",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"Nascondi quando stai caricando una foto",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"Disattiva stato di caricamento file",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"Nascondi quando stai caricando un file.",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"Disattiva stato di selezione posizione",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"Nascondi quando stai scegliendo una posizione.",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"Disattiva selezione contatto",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"Nascondi quando stai scegliendo un contatto.",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"Disattiva stato di gioco",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"Nascondi quando stai giocando.",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"Disattiva stato di registrazione video rotondo",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"Nascondi quando stai registrando un video rotondo.",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"Disattiva stato di caricamento video rotondo",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"Disattiva stato di parola in chiamata di gruppo",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"Nascondi quando stai parlando in una chiamata di gruppo.",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"Disattiva stato di selezione sticker",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"Nascondi quando stai scegliendo uno sticker.",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"Disattiva stato di interazione con emoji",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"Nascondi quando interagisci con un'emoji.",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"Disattiva stato di reazione con emoji",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"Nascondi quando reagisci con un'emoji a un messaggio.",
            @"READ_RECEIPTS": @"Conferme di lettura",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"Disattiva conferme di lettura messaggi",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"Impedisci agli altri di vedere che hai letto i loro messaggi.",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"Disattiva conferme di lettura storie",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"Impedisci agli altri di vedere che hai visualizzato le loro storie.",
            @"MISC": @"Varie",
            @"DISABLE_ALL_ADS_TITLE": @"Disattiva tutti gli annunci",
            @"DISABLE_ALL_ADS_SUBTITLE": @"Rimuove contenuti promozionali e annunci dall'app.",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"Consenti salvataggio contenuti protetti",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"Bypassa le restrizioni sul salvataggio dei contenuti protetti.",
            @"ANTI_REVOKE_TITLE": @"Anti-Revoca",
            @"ANTI_REVOKE_SUBTITLE": @"Mantieni i messaggi nella chat anche dopo che il mittente li elimina.",
            @"ANTI_SCREENSHOT_TITLE": @"Nascondi notifica screenshot",
            @"ANTI_SCREENSHOT_SUBTITLE": @"Impedisce l'invio di notifiche di screenshot nelle chat private e nei canali protetti.",
            @"FIX_FILE_PICKER_TITLE": @"Correggi selezione file",
            @"FIX_FILE_PICKER_SUBTITLE": @"Corregge il problema per cui non puoi selezionare file dall'app File nelle versioni sideloaded",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"Svuota cache selezione file",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"Poiché il selettore file copia i file in una directory temporanea, dobbiamo svuotarla manualmente",
            @"CACHE_CLEAR_WARNING_TITLE": @"Conferma",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"Sei sicuro?",
            @"ENABLE_FAKE_LOCATION_TITLE": @"Abilita falsificazione posizione",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"Ti consente di falsificare la posizione GPS del dispositivo",
            @"SELECT_FAKE_LOCATION_TITLE": @"Seleziona posizione",
            @"APPLY": @"Applica",
            @"APPLY_CHANGES": @"Sei sicuro di voler applicare queste modifiche?",
            @"OK": @"Ok",
            @"CANCEL": @"Annulla",
            @"DISCLAIMER": @"Avvertenza",
            @"AUTHOR_MESSAGE": @"Questa modifica per Telegram è solo per uso personale ed educativo. Non siamo in alcun modo affiliati con Telegram. Tutti i marchi, incluso il nome e il logo di Telegram, appartengono ai rispettivi proprietari. Non usare questo tweak per infrangere le regole, fare i furbi o violare i termini di Telegram — non siamo responsabili se qualcosa va storto. Usalo a tuo rischio e pericolo. \n\nInoltre… se ti piace, fammelo sapere. Vivo seriamente di approvazione. \n\nE se vuoi supportarmi con una donazione di uno o due dollari, contattami su Telegram.",
        };
    }
    if ([code isEqualToString:@"cn"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"隐身模式",
            @"READ_RECEIPT_SECTION_HEADER": @"阅读回执",
            @"MISC_SECTION_HEADER": @"其他",
            @"FILE_FIXER_SECTION_HEADER": @"文件选择器修复",
            @"FAKE_LOCATION_SECTION_HEADER": @"虚拟位置",
            @"LANGUAGE_SECTION_HEADER": @"语言",
            @"CREDITS_SECTION_HEADER": @"致谢",
            @"DISABLE_ONLINE_STATUS_TITLE": @"隐藏在线状态",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"防止他人看到你在线。",
            @"DISABLE_TYPING_STATUS_TITLE": @"隐藏输入状态",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"隐藏你正在输入的信息状态。",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"隐藏视频录制状态",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"隐藏你正在录制视频时的状态。",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"隐藏视频上传状态",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"上传视频时隐藏状态",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"隐藏语音消息录制状态",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"隐藏你正在录制语音消息时的状态。",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"隐藏语音消息上传状态",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"隐藏你正在上传语音消息时的状态。",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"隐藏照片上传状态",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"上传照片时隐藏状态",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"隐藏文件上传状态",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"隐藏你正在上传文件的状态。",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"隐藏选择位置状态",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"隐藏你正在选择位置的状态。",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"隐藏选择联系人状态",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"隐藏你正在选择联系人的状态。",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"隐藏游戏状态",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"隐藏你正在玩游戏的状态。",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"隐藏圆形视频录制状态",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"隐藏你正在录制圆形视频的状态。",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"隐藏圆形视频上传状态",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"隐藏群组通话发言状态",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"隐藏你在群组通话中发言时的状态。",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"隐藏选择贴纸状态",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"隐藏你正在选择贴纸的状态。",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"隐藏表情互动状态",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"隐藏你与表情互动时的状态。",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"隐藏表情反应状态",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"隐藏你用表情回应消息时的状态。",
            @"READ_RECEIPTS": @"已读回执",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"关闭消息已读回执",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"防止他人知道你已阅读消息。",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"关闭故事已读回执",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"防止他人知道你已查看故事。",
            @"MISC": @"其他",
            @"DISABLE_ALL_ADS_TITLE": @"关闭所有广告",
            @"DISABLE_ALL_ADS_SUBTITLE": @"移除应用中的广告和推广内容。",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"允许保存受保护内容",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"绕过限制，保存受保护的内容。",
            @"ANTI_REVOKE_TITLE": @"防撤回消息",
            @"ANTI_REVOKE_SUBTITLE": @"即使发送者删除了消息，也将其保留在聊天中。",
            @"ANTI_SCREENSHOT_TITLE": @"隐藏截屏通知",
            @"ANTI_SCREENSHOT_SUBTITLE": @"在私密聊天和受保护频道中截图时不发送通知。",
            @"FIX_FILE_PICKER_TITLE": @"修复文件选择器",
            @"FIX_FILE_PICKER_SUBTITLE": @"修复在侧载版本中无法从文件应用选择文件的问题",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"清除文件选择器缓存",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"由于文件选择器会将文件复制到临时目录，需要手动清除",
            @"CACHE_CLEAR_WARNING_TITLE": @"确认",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"你确定吗？",
            @"ENABLE_FAKE_LOCATION_TITLE": @"启用虚拟位置",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"允许伪装设备的 GPS 位置",
            @"SELECT_FAKE_LOCATION_TITLE": @"选择位置",
            @"APPLY": @"应用",
            @"APPLY_CHANGES": @"您确定要应用这些更改吗？",
            @"OK": @"确定",
            @"CANCEL": @"取消",
            @"AUTHOR_MESSAGE": @"此 Telegram 插件仅供个人和教育用途。我们与 Telegram 没有任何关联。所有商标，包括 Telegram 的名称和标志，均归其各自所有者所有。请不要用它来违反规则、做灰色操作或违反 Telegram 的服务条款——如果出问题，我们概不负责。使用风险自负。\n\n另外……如果你喜欢这个插件，记得说一声。我真的很需要认可来维持动力。\n\n还有……如果你愿意支持我，捐个一两美元的话，可以在 Telegram 上联系我。",
        };
    }
    if ([code isEqualToString:@"ru"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"Режим призрака",
            @"READ_RECEIPT_SECTION_HEADER": @"Отчёты о прочтении",
            @"MISC_SECTION_HEADER": @"Приватность и функции",
            @"FILE_FIXER_SECTION_HEADER": @"Исправление выбора файлов",
            @"FAKE_LOCATION_SECTION_HEADER": @"Фейковая геолокация",
            @"LANGUAGE_SECTION_HEADER": @"Язык",
            @"CREDITS_SECTION_HEADER": @"Благодарности",
            @"DISABLE_ONLINE_STATUS_TITLE": @"Скрыть онлайн-статус",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"Не показывать другим, что вы в сети.",
            @"DISABLE_TYPING_STATUS_TITLE": @"Скрыть статус набора",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"Не показывать, что вы печатаете сообщение.",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"Скрыть статус записи видео",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"Не показывать, что вы записываете видео.",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"Скрыть статус загрузки видео",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"Скрывать при загрузке видео",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"Скрыть запись голосового сообщения",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"Не показывать, что вы записываете голосовое сообщение.",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"Скрыть загрузку голосового сообщения",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"Не показывать, что вы загружаете голосовое сообщение.",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"Скрыть статус загрузки фото",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"Скрывать при загрузке фото",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"Скрыть статус загрузки файла",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"Не показывать, что вы загружаете файл.",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"Скрыть выбор локации",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"Не показывать, что вы выбираете местоположение.",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"Скрыть выбор контакта",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"Не показывать, что вы выбираете контакт.",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"Скрыть игру",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"Не показывать, что вы играете в игру.",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"Скрыть запись круглого видео",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"Не показывать, что вы записываете круглое видео.",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"Скрыть загрузку круглого видео",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"Скрыть голос в групповом звонке",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"Не показывать, что вы говорите в групповом звонке.",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"Скрыть выбор стикера",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"Не показывать, что вы выбираете стикер.",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"Скрыть взаимодействие с эмодзи",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"Не показывать, что вы взаимодействуете с эмодзи.",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"Скрыть реакцию эмодзи",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"Не показывать, что вы реагируете на сообщение эмодзи.",
            @"READ_RECEIPTS": @"Отчёты о прочтении",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"Отключить отчёты о прочтении сообщений",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"Не сообщать, что вы прочитали сообщение.",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"Отключить отчёты о прочтении историй",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"Не сообщать, что вы просмотрели историю.",
            @"MISC": @"Разное",
            @"DISABLE_ALL_ADS_TITLE": @"Отключить всю рекламу",
            @"DISABLE_ALL_ADS_SUBTITLE": @"Убирает спонсорские сообщения и рекламный контент из приложения.",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"Сохранение медиа из закрытых чатов",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"Обходит запрет пересылки — сохраняй и пересылай медиа из защищённых каналов и чатов.",
            @"ANTI_REVOKE_TITLE": @"Сохранять удалённые сообщения",
            @"ANTI_REVOKE_SUBTITLE": @"Сообщения остаются у вас в чате даже после того, как отправитель их удалил.",
            @"ANTI_EDIT_TITLE": @"Сохранять оригинал при редактировании",
            @"ANTI_EDIT_SUBTITLE": @"Когда кто-то редактирует сообщение, вы видите первоначальный текст — до правки.",
            @"ANTI_SCREENSHOT_TITLE": @"Скриншоты без уведомлений",
            @"ANTI_SCREENSHOT_SUBTITLE": @"Делайте скриншоты в секретных чатах и защищённых каналах — без уведомления собеседника.",
            @"ANTI_SELF_DESTRUCT_TITLE": @"Просмотр исчезающих медиафайлов",
            @"ANTI_SELF_DESTRUCT_SUBTITLE": @"Открывайте одноразовые и исчезающие фото/видео без запуска таймера самоуничтожения. Медиафайл остаётся доступным локально.",
            @"FIX_FILE_PICKER_TITLE": @"Исправить выбор файлов",
            @"FIX_FILE_PICKER_SUBTITLE": @"Исправляет ошибку, из-за которой невозможно выбрать файлы из приложения 'Файлы' на установленных вручную версиях",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"Очистить кэш выбора файлов",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"Поскольку файлы копируются в временную папку, кэш нужно очищать вручную",
            @"CACHE_CLEAR_WARNING_TITLE": @"Подтвердить",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"Вы уверены?",
            @"ENABLE_FAKE_LOCATION_TITLE": @"Включить фейковую геолокацию",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"Позволяет подделывать GPS-локацию устройства",
            @"SELECT_FAKE_LOCATION_TITLE": @"Выбрать местоположение",
            @"APPLY": @"Применить",
            @"APPLY_CHANGES": @"Вы уверены, что хотите применить эти изменения?",
            @"OK": @"Ок",
            @"CANCEL": @"Отмена",
            @"DISCLAIMER": @"Отказ от ответственности",
            @"AUTHOR_MESSAGE": @"Этот твик для Telegram предназначен только для личного и образовательного использования. Мы никоим образом не связаны с Telegram. Все торговые марки, включая название и логотип Telegram, принадлежат их владельцам. Не используйте это для нарушения правил, сомнительных действий или нарушений условий использования Telegram — мы не несем ответственности, если что-то пойдет не так. Используйте на свой страх и риск.\n\nА ещё… если тебе понравилось — скажи об этом. Я, честно говоря, питаюсь одобрением.\n\nИ… если хочешь поддержать меня и скинуть доллар-другой, напиши мне в Telegram.",
        };
    }
    if ([code isEqualToString:@"fr"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"Mode Fantôme",
            @"READ_RECEIPT_SECTION_HEADER": @"Accusés de Lecture",
            @"MISC_SECTION_HEADER": @"Divers",
            @"FILE_FIXER_SECTION_HEADER": @"Correcteur de Sélecteur de Fichiers",
            @"FAKE_LOCATION_SECTION_HEADER": @"Fausse Localisation",
            @"LANGUAGE_SECTION_HEADER": @"Langue",
            @"CREDITS_SECTION_HEADER": @"Crédits",
            @"DISABLE_ONLINE_STATUS_TITLE": @"Désactiver le statut en ligne",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en ligne.",
            @"DISABLE_TYPING_STATUS_TITLE": @"Désactiver le statut de saisie",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train d'écrire.",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"Désactiver le statut d'enregistrement vidéo",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train d'enregistrer une vidéo.",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"Désactiver le statut de téléchargement de vidéo",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"Masquer lors du téléchargement d'une vidéo",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"Désactiver l'enregistrement de messages vocaux",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train d'enregistrer un message vocal.",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"Désactiver le statut de téléchargement de message vocal",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train de télécharger un message vocal.",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"Désactiver le statut de téléchargement de photo",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"Masquer lors du téléchargement d'une photo",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"Désactiver le statut de téléchargement de fichier",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train de télécharger un fichier.",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"Désactiver le choix du lieu",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train de choisir un lieu.",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"Désactiver le choix du contact",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"Ne pas afficher que vous êtes en train de choisir un contact.",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"Désactiver le statut de jeu",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train de jouer.",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"Désactiver l'enregistrement de vidéo ronde",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train d'enregistrer une vidéo ronde.",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"Désactiver le statut de téléchargement de vidéo ronde",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"Désactiver le statut de parole dans les appels de groupe",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"Ne pas afficher que vous parlez dans un appel de groupe.",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"Désactiver le choix de stickers",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"Ne pas afficher que vous êtes en train de choisir un sticker.",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"Désactiver l'interaction avec les émojis",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"Ne pas afficher que vous interagissez avec un émoji.",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"Désactiver la reconnaissance des émojis",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"Ne pas afficher que vous avez reconnu un émoji.",
            @"READ_RECEIPTS": @"Accusés de réception",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"Désactiver les accusés de réception de message",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"Ne pas afficher que vous avez lu le message.",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"Désactiver les accusés de réception des stories",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"Ne pas afficher que vous avez vu la story.",
            @"MISC": @"Divers",
            @"DISABLE_ALL_ADS_TITLE": @"Désactiver toutes les publicités",
            @"DISABLE_ALL_ADS_SUBTITLE": @"Supprimer les publicités et le contenu sponsorisé de l'application.",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"Activer l'enregistrement de contenu protégé",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"Contournement des restrictions pour enregistrer le contenu protégé.",
            @"ANTI_REVOKE_TITLE": @"Anti-Révocation",
            @"ANTI_REVOKE_SUBTITLE": @"Conserve les messages dans le chat même après leur suppression par l'expéditeur.",
            @"ANTI_SCREENSHOT_TITLE": @"Masquer la notif. capture",
            @"ANTI_SCREENSHOT_SUBTITLE": @"Empêche l'envoi de notification lors de captures dans les chats secrets et chaînes protégées.",
            @"FIX_FILE_PICKER_TITLE": @"Corriger le Sélecteur de Fichiers",
            @"FIX_FILE_PICKER_SUBTITLE": @"Corrige le problème empêchant la sélection de fichiers depuis l’app Fichiers sur les versions installées manuellement",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"Vider le Cache du Sélecteur de Fichiers",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"Comme le sélecteur copie les fichiers dans un dossier temporaire, il faut le vider manuellement",
            @"CACHE_CLEAR_WARNING_TITLE": @"Confirmer",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"Êtes-vous sûr ?",
            @"ENABLE_FAKE_LOCATION_TITLE": @"Activer la Fausse Localisation",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"Permet de simuler la localisation GPS de votre appareil",
            @"SELECT_FAKE_LOCATION_TITLE": @"Sélectionner une Localisation",
            @"APPLY": @"Appliquer",
            @"APPLY_CHANGES": @"Êtes-vous sûr de vouloir appliquer ces changements ?",
            @"OK": @"OK",
            @"CANCEL": @"Annuler",
            @"AUTHOR_MESSAGE": @"Ce tweak Telegram est uniquement destiné à un usage personnel et éducatif. Nous ne sommes en aucun cas affiliés à Telegram. Toutes les marques, y compris le nom et le logo de Telegram, appartiennent à leurs propriétaires respectifs. N'utilisez pas ceci pour enfreindre les règles, faire des choses louches ou violer les conditions d'utilisation de Telegram — nous ne sommes pas responsables en cas de problème. Utilisez-le à vos risques et périls.\n\nAussi… si ça vous plaît, dites-le. Sérieusement, je vis pour la validation.\n\nEt… si vous voulez me soutenir avec un ou deux euros, contactez-moi sur Telegram.",
        };
    }
    if ([code isEqualToString:@"vn"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"Chế độ ma",
            @"READ_RECEIPT_SECTION_HEADER": @"Trạng thái đã đọc",
            @"MISC_SECTION_HEADER": @"Khác",
            @"FILE_FIXER_SECTION_HEADER": @"Sửa lỗi chọn tệp",
            @"FAKE_LOCATION_SECTION_HEADER": @"Vị trí giả",
            @"LANGUAGE_SECTION_HEADER": @"Ngôn ngữ",
            @"CREDITS_SECTION_HEADER": @"Ghi công",
            @"DISABLE_ONLINE_STATUS_TITLE": @"Tắt trạng thái online",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"Ngăn người khác thấy bạn đang online.",
            @"DISABLE_TYPING_STATUS_TITLE": @"Tắt trạng thái đang nhập",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"Ẩn khi bạn đang soạn tin nhắn.",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"Tắt trạng thái đang quay video",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"Ẩn khi bạn đang quay video.",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"Tắt trạng thái đang tải lên video",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"Ẩn khi bạn đang tải video lên",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"Tắt trạng thái đang ghi âm",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"Ẩn khi bạn đang ghi âm tin nhắn.",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"Tắt trạng thái đang tải lên tin nhắn thoại",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"Ẩn khi bạn đang tải tin nhắn thoại lên.",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"Tắt trạng thái đang tải ảnh lên",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"Ẩn khi bạn đang tải ảnh lên",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"Tắt trạng thái đang tải tệp lên",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"Ẩn khi bạn đang tải tệp lên.",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"Tắt trạng thái đang chọn vị trí",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"Ẩn khi bạn đang chọn vị trí.",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"Tắt trạng thái đang chọn liên hệ",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"Ẩn khi bạn đang chọn liên hệ.",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"Tắt trạng thái đang chơi game",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"Ẩn khi bạn đang chơi trò chơi.",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"Tắt trạng thái đang quay video tròn",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"Ẩn khi bạn đang quay video tròn.",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"Tắt trạng thái đang tải video tròn lên",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"Tắt trạng thái đang nói trong cuộc gọi nhóm",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"Ẩn khi bạn đang nói trong cuộc gọi nhóm.",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"Tắt trạng thái đang chọn nhãn dán",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"Ẩn khi bạn đang chọn nhãn dán.",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"Tắt trạng thái tương tác emoji",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"Ẩn khi bạn tương tác bằng emoji.",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"Tắt trạng thái phản ứng emoji",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"Ẩn khi bạn dùng emoji phản ứng tin nhắn.",
            @"READ_RECEIPTS": @"Trạng thái đã đọc",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"Tắt trạng thái đã đọc tin nhắn",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"Ngăn người khác thấy bạn đã đọc tin nhắn của họ.",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"Tắt trạng thái đã xem story",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"Ngăn người khác thấy bạn đã xem story của họ.",
            @"MISC": @"Khác",
            @"DISABLE_ALL_ADS_TITLE": @"Chặn tất cả quảng cáo",
            @"DISABLE_ALL_ADS_SUBTITLE": @"Loại bỏ nội dung quảng cáo khỏi ứng dụng.",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"Cho phép lưu nội dung được bảo vệ",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"Cho phép lưu và chụp ảnh màn hình nội dung được bảo vệ.",
            @"ANTI_REVOKE_TITLE": @"Chống thu hồi tin nhắn",
            @"ANTI_REVOKE_SUBTITLE": @"Giữ tin nhắn trong cuộc trò chuyện kể cả khi người gửi đã xóa.",
            @"ANTI_SCREENSHOT_TITLE": @"Ẩn thông báo chụp màn hình",
            @"ANTI_SCREENSHOT_SUBTITLE": @"Không gửi thông báo chụp màn hình trong đoạn chat bí mật và kênh được bảo vệ.",
            @"FIX_FILE_PICKER_TITLE": @"Sửa lỗi chọn tệp",
            @"FIX_FILE_PICKER_SUBTITLE": @"Khắc phục lỗi không thể chọn tệp từ ứng dụng Files trên bản sideload",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"Xóa bộ nhớ đệm chọn tệp",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"Vì File Picker sao chép tệp vào thư mục tạm, cần xóa thủ công",
            @"CACHE_CLEAR_WARNING_TITLE": @"Xác nhận",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"Bạn có chắc chắn?",
            @"ENABLE_FAKE_LOCATION_TITLE": @"Bật giả mạo vị trí",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"Cho phép giả mạo vị trí GPS của thiết bị",
            @"SELECT_FAKE_LOCATION_TITLE": @"Chọn vị trí",
            @"APPLY": @"Áp dụng",
            @"APPLY_CHANGES": @"Bạn có chắc muốn áp dụng các thay đổi này?",
            @"OK": @"Đồng ý",
            @"CANCEL": @"Hủy",
            @"DISCLAIMER": @"Tuyên bố miễn trừ",
            @"AUTHOR_MESSAGE": @"Bản chỉnh sửa Telegram này chỉ dành cho mục đích cá nhân và giáo dục. Chúng tôi không liên kết với Telegram. Mọi nhãn hiệu, bao gồm tên và logo Telegram, thuộc về chủ sở hữu tương ứng. Không sử dụng để vi phạm quy tắc, hành vi mờ ám hoặc điều khoản Telegram - chúng tôi không chịu trách nhiệm nếu có vấn đề phát sinh. Tự chịu rủi ro khi sử dụng. \n \nNếu bạn thích, hãy nói gì đó. Tôi thực sự sống nhờ sự công nhận. \n \nNếu muốn hỗ trợ tôi bằng cách quyên góp, hãy liên hệ với tôi trên Telegram",
        };
    }
    if ([code isEqualToString:@"tw"]) {
        return @{
            @"GHOST_MODE_SECTION_HEADER": @"隱身模式",
            @"READ_RECEIPT_SECTION_HEADER": @"已讀通知",
            @"MISC_SECTION_HEADER": @"其它",
            @"FILE_FIXER_SECTION_HEADER": @"檔案選擇器修復",
            @"FAKE_LOCATION_SECTION_HEADER": @"虛擬定位",
            @"LANGUAGE_SECTION_HEADER": @"語言",
            @"CREDITS_SECTION_HEADER": @"鳴謝",
            @"DISABLE_ONLINE_STATUS_TITLE": @"停用在線狀態",
            @"DISABLE_ONLINE_STATUS_SUBTITLE": @"防止他人看到你正在線上",
            @"DISABLE_TYPING_STATUS_TITLE": @"停用輸入狀態",
            @"DISABLE_TYPING_STATUS_SUBTITLE": @"隱藏你正在輸入訊息的狀態",
            @"DISABLE_RECORDING_VIDEO_STATUS_TITLE": @"停用錄影狀態",
            @"DISABLE_RECORDING_VIDEO_STATUS_SUBTITLE": @"隱藏你正在錄製影片的狀態",
            @"DISABLE_UPLOADING_VIDEO_STATUS_TITLE": @"停用上傳影片狀態",
            @"DISABLE_UPLOADING_VIDEO_STATUS_SUBTITLE": @"隱藏你正在上傳影片的狀態",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_TITLE": @"停用語音訊息錄製狀態",
            @"DISABLE_VC_MESSAGE_RECORDING_STATUS_SUBTITLE": @"隱藏你正在錄製語音訊息的狀態",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_TITLE": @"停用語音訊息上傳狀態",
            @"DISABLE_VC_MESSAGE_UPLOADING_STATUS_SUBTITLE": @"隱藏你正在上傳語音訊息的狀態",
            @"DISABLE_UPLOADING_PHOTO_STATUS_TITLE": @"停用上傳照片狀態",
            @"DISABLE_UPLOADING_PHOTO_STATUS_SUBTITLE": @"隱藏你正在上傳照片的狀態",
            @"DISABLE_UPLOADING_FILE_STATUS_TITLE": @"停用上傳檔案狀態",
            @"DISABLE_UPLOADING_FILE_STATUS_SUBTITLE": @"隱藏你正在上傳檔案的狀態",
            @"DISABLE_CHOOSING_LOCATION_STATUS_TITLE": @"停用選擇位置狀態",
            @"DISABLE_CHOOSING_LOCATION_STATUS_SUBTITLE": @"隱藏你正在選擇位置的狀態",
            @"DISABLE_CHOOSING_CONTACT_TITLE": @"停用選擇聯絡人",
            @"DISABLE_CHOOSING_CONTACT_SUBTITLE": @"隱藏你正在選擇聯絡人的狀態",
            @"DISABLE_PLAYING_GAME_STATUS_TITLE": @"停用遊戲狀態",
            @"DISABLE_PLAYING_GAME_STATUS_SUBTITLE": @"隱藏你正在玩遊戲的狀態",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_TITLE": @"停用錄製圓形影片狀態",
            @"DISABLE_RECORDING_ROUND_VIDEO_STATUS_SUBTITLE": @"隱藏你正在錄製圓形影片的狀態",
            @"DISABLE_UPLOADING_ROUND_VIDEO_STATUS_TITLE": @"停用上傳圓形影片狀態",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_TITLE": @"停用群組通話說話狀態",
            @"DISABLE_SPEAKING_IN_GROUP_CALL_STATUS_SUBTITLE": @"隱藏你正在群組通話中說話的狀態",
            @"DISABLE_CHOOSING_STICKER_STATUS_TITLE": @"停用選擇貼圖狀態",
            @"DISABLE_CHOOSING_STICKER_STATUS_SUBTITLE": @"隱藏你正在挑選貼圖的狀態",
            @"DISABLE_EMOJI_INTERACTION_STATUS_TITLE": @"停用表情符號互動狀態",
            @"DISABLE_EMOJI_INTERACTION_STATUS_SUBTITLE": @"隱藏你與表情符號互動的狀態",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_TITLE": @"停用表情符號回應狀態",
            @"DISABLE_EMOJI_ACKNOWLEDGEMENT_STATUS_SUBTITLE": @"隱藏你使用表情符號回應訊息的狀態",
            @"READ_RECEIPTS": @"已讀通知",
            @"DISABLE_MESSAGE_READ_RECEIPT_TITLE": @"停用訊息已讀通知",
            @"DISABLE_MESSAGE_READ_RECEIPT_SUBTITLE": @"防止他人看到你已閱讀他們的訊息",
            @"DISABLE_STORY_READ_RECEIPT_TITLE": @"停用限時動態已讀通知",
            @"DISABLE_STORY_READ_RECEIPT_SUBTITLE": @"防止他人看到你已查看他們的動態",
            @"MISC": @"其它",
            @"DISABLE_ALL_ADS_TITLE": @"停用所有廣告",
            @"DISABLE_ALL_ADS_SUBTITLE": @"移除應用程式中的廣告及促銷內容",
            @"ENABLE_SAVING_PROTECTED_CONTENT_TITLE": @"允許儲存受保護內容",
            @"ENABLE_SAVING_PROTECTED_CONTENT_SUBTITLE": @"繞過儲存受保護內容的限制",
            @"ANTI_REVOKE_TITLE": @"防撤回訊息",
            @"ANTI_REVOKE_SUBTITLE": @"即使發送者刪除訊息，也保留在聊天中。",
            @"ANTI_SCREENSHOT_TITLE": @"隱藏截圖通知",
            @"ANTI_SCREENSHOT_SUBTITLE": @"在私密聊天和受保護頻道中截圖時不發送通知。",
            @"FIX_FILE_PICKER_TITLE": @"修復檔案選擇器",
            @"FIX_FILE_PICKER_SUBTITLE": @"修復側載版本無法從檔案應用程式選擇檔案的問題",
            @"CLEAR_FILE_PICKER_CACHE_TITLE": @"清除檔案選擇器快取",
            @"CLEAR_FILE_PICKER_CACHE_SUBTITLE": @"由於檔案選擇器會將檔案複製到臨時目錄，需手動清除快取",
            @"CACHE_CLEAR_WARNING_TITLE": @"確認",
            @"CACHE_CLEAR_WARNING_MESSAGE": @"你確定嗎？",
            @"ENABLE_FAKE_LOCATION_TITLE": @"啟用虛擬定位",
            @"ENABLE_FAKE_LOCATION_SUBTITLE": @"允許你偽裝設備的GPS位置",
            @"SELECT_FAKE_LOCATION_TITLE": @"選擇位置",
            @"APPLY": @"套用",
            @"APPLY_CHANGES": @"你確定要套用這些變更嗎？",
            @"OK": @"確定",
            @"CANCEL": @"取消",
            @"DISCLAIMER": @"免責聲明",
            @"AUTHOR_MESSAGE": @"本Telegram調整工具僅限於個人及教育用途。我們與Telegram無任何關聯。所有商標，包括Telegram名稱及標誌，皆屬其各自所有者所有。請勿使用本工具違反規則、進行不當行為或違反Telegram的服務條款。若因使用本工具而產生任何問題，我們概不負責，使用者須自行承擔風險。\n \n此外，若您對本工具感到滿意，歡迎提供意見或反饋，您的支持對我們至關重要。\n \n如有意透過小額捐款支持我，請透過Telegram與我聯繫。",
        };
    }
    return nil;
}
